# Generated by Django 5.1.4 on 2025-01-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0004_alter_user_options_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='صافي الربح'),
        ),
    ]
