# Generated by Django 5.1.4 on 2025-01-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0006_systemsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
