# Generated by Django 5.1.4 on 2025-01-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0008_deliveryperson_net_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_minutes', models.IntegerField(default=0)),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
