# Generated by Django 5.1.4 on 2025-01-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0010_remove_employee_advances_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='base_salary',
            new_name='salary',
        ),
    ]
