# Generated by Django 5.1.4 on 2025-01-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0014_employee_action_details_employee_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='action_details',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='action_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
