# Generated by Django 5.1.4 on 2025-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0015_remove_employee_action_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='loan_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
