# Generated by Django 5.1.4 on 2025-01-06 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0016_employee_loan_taken_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='loan_taken',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='loan_taken_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='penalty_per_minute',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='penalty_reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_after_penalty',
        ),
        migrations.CreateModel(
            name='EmployeeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='otlop.employee')),
            ],
        ),
    ]
