# Generated by Django 5.1.4 on 2025-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0017_remove_employee_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employeeaction',
            name='reason',
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='loan_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='penalty_reason',
            field=models.TextField(blank=True, default='لا يوجد سبب', null=True),
        ),
    ]
