# Generated by Django 5.1.4 on 2025-01-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0018_remove_employeeaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='loan_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='loan_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalty_per_minute',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalty_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_after_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
