# Generated by Django 5.1.4 on 2025-01-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0019_employee_discount_amount_employee_late_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='loan_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
