# Generated by Django 5.1.4 on 2025-01-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0020_employeeaction_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaction',
            name='date',
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='penalty_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
