# Generated by Django 5.1.4 on 2025-01-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0022_remove_employee_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
