# Generated by Django 5.1.4 on 2025-01-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0023_employee_discount_amount_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
