# Generated by Django 5.1.4 on 2025-01-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlop', '0024_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='غير محدد', max_length=15),
        ),
    ]
